### PR TITLE
Add more attribute getters

### PR DESCRIPTION
**Pull request by chtenb**
This PR adds more attribute getters to support more Identity Providers out of the box.

### CODE REVIEW

**Comment by alex-jitbit** [comment]
Thanks! But why did you remove the `GetCustomAttribute` method?

**Comment by chtenb** [comment]
That wasn't my intention at all! Must have slipped into the PR by accident. Will fix.

**Comment by chtenb** [comment]
@alex-jitbit Fixed

**Review by hey24sheep — APPROVED** [review]
LGTM, Can we merge this? @alex-jitbit

**Comment by alex-jitbit** [comment]
Sorry @Chiel92  @hey24sheep finally got time to get back to this

**Pull request merged**
