### PR TITLE
Added ForceAuthn support

### PR DESCRIPTION
**Pull request by cbroxton**
Added support for adding the "ForceAuthn" attribute

https://wiki.shibboleth.net/confluence/display/SP3/ForceAuthn

### CODE REVIEW

**Comment by alex-jitbit** [comment]
1) I don't like that there's no way to send a request WITHOUT this attribute..
2) Shouldn't it be lowercase? Like `forceAuthn="true"` ?

**Comment by cbroxton** [comment]
1) Have made it nullable so it will just be excluded if a value isn't set.
2) Ye you're probably right, have changed.

**Comment by cbroxton** [comment]
@alex-jitbit This should be ready to re-test now

**Comment by alex-jitbit** [comment]
I've added this as a separate commit 55bd562b29145de98fff41a81d5d30a9073592d6 due to a recent file rename/move

**Pull request closed without merging**
